apiVersion: apps/v1
kind: Deployment
metadata:
  name: emsapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-db
  template:
    metadata:
      labels:
        app: ems-db
    spec:
      containers:
      - name: k8s-ems
        image: mvikhe/emsapp
        ports:
        - name: http-port
          containerPort: 8082
        env:
          - name: MYSQL_HOST
            value: mysqldb
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ems-secrets
                key: rootPassword
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ems-secrets
                key: database


